Merge après itération 3
ErabliereApi/ErabliereApi pull request #262
Opened 2024-05-11 20:07 UTC by Sam-Existence

- Début de page admin (gestion des utilisateurs)
- Amélioration de la table CustomerErablieres
- Correction du bug qui redirigeait l'utilisateur vers la page principale après être allé à une URL directement
- Amélioration des validations des formulaires note
- Amélioration du dashboard et correction de l'issue #259

2024-05-11 21:17 UTC, freddycoder commented
Merci beaucoup Samantha, je regarde ça demain, je vois plusieurs problème soulevé par sonarcube sur la migration entity framework, pas besoin de corriger cela. Je vais voir pour ajuster les paramètres de l'outils pour pas analyser les migrations.

2024-05-13 00:01 UTC, freddycoder requested changes
Je ne pourrait pas merger la PR tel quel du au problème de la migration BD. Je propose donc deux approches.

1. Je vous laisse regarder pour corriger le problème pour que l'intégration fonctionne sans problème, mais j'ai peur que ça soit peut-être long et difficle. Je serais à l'aise si on procède autrement.
2. Je vais créer une branche intégration dans le repos principal, comme ça je vais pouvoir merger le code et régler les problèmes d'intégration sans modifier la branche master qui est connecté au pipeline de déploiement. Une fois que ça sera bon je ferais le merge dans la master moi même.

J'irais pour l'option 2 car comme ça vous pourriez continuer sur les nouvelles fonctionnalité au lieu de passer du temps sur des problèmes d'environnements.

2024-05-13 01:16 UTC, Sam-Existence commented on ErabliereApi/Controllers/CustomersController.cs
> -    public async Task<IActionResult> DeleteCustomerAccessAdmin(Guid id, CancellationToken token)
Puisque j'ai supprimé la clé unique de la table CustomerErablieres et la remplacer avec une clé composée, c'est maintenant impossible de supprimer un enregistrement avec un seul id, il faut le customerId et le erabliereId pour le supprimer. J'ai donc pensé que cette route n'avait plus de sens.

2024-05-13 01:18 UTC, Sam-Existence commented on ErabliereApi/Depot/Sql/Migrations/20240426172618_CorrectionCustomerErablieresForeignKey.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
C'est bizzare que je n'aie pas eu cette erreur, je vais regarder ça.

2024-05-13 01:46 UTC, Sam-Existence commented on ErabliereApi/Depot/Sql/Migrations/20240426172618_CorrectionCustomerErablieresForeignKey.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
Est-ce que c'est possible qu'il y a un enregistrement dans la table CustomerErablieres qui a un IdErabliere qui n'existe plus?

2024-05-13 01:49 UTC, freddycoder commented on ErabliereApi/Controllers/CustomersController.cs
> -    public async Task<IActionResult> DeleteCustomerAccessAdmin(Guid id, CancellationToken token)
Ok je vois, est-ce que le bouton pour supprimer un accès utilisateur fonctionne encore ?

2024-05-13 01:50 UTC, freddycoder commented on ErabliereApi/Depot/Sql/Migrations/20240426172618_CorrectionCustomerErablieresForeignKey.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
Je regarde demain et je te dis cela. Bien pensé

2024-05-13 02:19 UTC, Sam-Existence commented on ErabliereModel/Erabliere.cs
> +    public List<CustomerErabliere>? CustomerErablieres { get; set; }
Après un peu de testing, on dirait que le [JsonIgnore] empêche le $expand sans ne rien briser.
![image](https://github.com/ErabliereApi/ErabliereApi/assets/54251068/f03ede38-2199-418e-aa77-9bbfd4042913)

2024-05-13 03:33 UTC, Sam-Existence commented on ErabliereApi/Controllers/CustomersController.cs
> -    public async Task<IActionResult> DeleteCustomerAccessAdmin(Guid id, CancellationToken token)
Oui, le bouton utilise la route DELETE /Erablieres/{idErabliere}/CustomersAccess/{idCustomer}

2024-05-13 10:42 UTC, freddycoder commented on ErabliereApi/Depot/Sql/Migrations/20240426172618_CorrectionCustomerErablieresForeignKey.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
Effectivement, ça fonctionne bien après avoir fait le ménage dans la base de données de test.

Je vais devoir aussi faire le nettoyage dans la BD de prod. Je te tiens au courant s'il y a autre chose pour cette PR. Merci!

2024-05-13 11:10 UTC, merged